### PR TITLE
A BDV render settings editor panel.

### PR DESCRIPTION
**Pull request by tinevez**
A BDV render settings editor panel.  This is the one you get when you press 'R' in a BDV window.
- Adapted from the TrackStyle framework,
- Displays a list of differente render settings.
- Can load / save from disk.
- Have protected defaults.

### CODE REVIEW

**Comment by tpietzsch** [comment]
When the settings dialog opens, it is too small to show the sliders as sliders:
screen shot 2016-09-21 at 15 24 55

**Comment by tpietzsch** [comment]
When the dialog is enlarged (to show the sliders) the separating lines look weird
screen shot 2016-09-21 at 15 25 22

IMO, the solution is to make panels for groups of items ("Colors and look", "Links", ...) and add title borders. Here is an example from something similar in BDV:
```java
		groupingPanel = new GroupingPanel( visibilityAndGrouping );
		visibilityAndGrouping.addUpdateListener( groupingPanel );
		groupingPanel.setBorder( BorderFactory.createCompoundBorder(
				BorderFactory.createEmptyBorder( 4, 2, 4, 2 ),
				BorderFactory.createCompoundBorder(
						BorderFactory.createTitledBorder(
								BorderFactory.createEtchedBorder(),
								"grouping" ),
						BorderFactory.createEmptyBorder( 2, 2, 2, 2 ) ) ) );
```
Probably it can be tuned to make it look similar to what you have now

**Comment by tinevez** [comment]
Reworked the render settings panel.
- It has a shared list of styles.
- The panel resizes properly.

**Comment by tinevez** [comment]
Rework the render settings system.

* Each RS dialog shares a common list of styles. 
This has limitations: 
** if a style is deleted in a dialog, other dialogs know, unless one of them has the deleted style. Then this one is not changed. 
** if a style is edited in a dialog, other dialogs with this style are not updated unless they reselect this dialog.

* Rework the resizing of the panel.

**Comment by tinevez** [comment]
Rework the render settings system.

* Each RS dialog shares a common list of styles. 
This has limitations: 
** if a style is deleted in a dialog, other dialogs know, unless one of them has the deleted style. Then this one is not changed. 
** if a style is edited in a dialog, other dialogs with this style are not updated unless they reselect this dialog.

* Rework the resizing of the panel.

**Comment by tinevez** [comment]
@tpietzsch good to go?

**Pull request closed without merging**
